apiVersion: v1
kind: Service
metadata:
  name: healthylinkx-ux-service
  labels:
    app: healthylinkx-ux
spec:
  type: NodePort
  ports:
  - port: 3000
    nodePort: 30200
    protocol: TCP
    name: http
  selector:
    app: healthylinkx-ux